FROM ruby:alpine

# Install base packages
RUN apk update && apk upgrade
RUN apk add curl wget bash

# Install ruby and ruby-bundler
RUN apk add ruby ruby-bundler ruby-irb libffi-dev vim

# Clean APK cache
RUN rm -rf /var/cache/apk/*

# Copy sinatra app into docker and configure
RUN mkdir /root/barmate
WORKDIR /root/barmate
COPY . /root/barmate
RUN bundle